---
title             : "Subjective Wellbeing"
shorttitle        : "SWB Outcomes"

author: 
  - name          : "Aaron Willcox"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "2/69 Dorking Road "
    email         : "aaron@willcox.io"
  - name          : ""
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "Deakin University"
  - id            : "2"
    institution   : "Konstanz Business School"

author_note: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "Subjective Wellbeing. Personality, Big Five, Multiple Discrepancies Theory"
wordcount         : "3000"

bibliography      : ["references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
mask              : no

class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

## Introduction
Insert a citation like [@RN584]

# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

# Results
```{r}
library(dplyr)

# Calculate summary statistics


# Print table in APA format

# papaja::apa_table(., caption = "Descriptive statistics of SWB measure by outcome")
```


# Discussion


\newpage

# References
```{r create_r-references}
#r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
